kafka:
  version: 0.8.2.1
  scala_version: 2.11
  mirror: http://apache.dataguru.cn
  data_dir: /var/lib/kafka
  install_dir: "/etc"
# This does not have to be every Zookeeper host, but the more the better
#  by default, we assume this is run at the same time as Zookeeper provisioning
zk_hosts: "{{ groups['zk'] }}" # This does not have to be every Zookeeper host
zk_client_port: 2181 # Should be set properly if not using Vagrant
# kafka_cluster_info: "{{ vagrant_kafka_cluster_info }}"
# If not using Vagrant,
# Should be a list of node hostnames to node info
# Example:
kafka_cluster_info:
  master01:
    broker_id: 1
  master02:
    broker_id: 2
  master03:
    broker_id: 3
